import { BoxTemplate, Product } from './types';

export const PRODUCTS: Record<string, Product> = {
  prod_001: {
    id: 'prod_001',
    name: 'Tomate Larga Vida',
    category: 'verdura',
    unit: 'kg',
    step: 0.5,
    basePrice: 1500,
    isSwappable: true,
    inSeason: true,
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&q=80&w=300',
    tags: ['local', 'fresco'],
  },
  prod_002: {
    id: 'prod_002',
    name: 'Palta Hass',
    category: 'fruta',
    unit: 'kg',
    step: 0.5,
    basePrice: 4500,
    isSwappable: true,
    inSeason: true,
    imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&q=80&w=300',
    tags: ['premium'],
  },
  prod_003: {
    id: 'prod_003',
    name: 'Zanahoria',
    category: 'verdura',
    unit: 'kg',
    step: 0.5,
    basePrice: 1000,
    isSwappable: true,
    inSeason: true,
    imageUrl: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&q=80&w=300',
    tags: ['fresco'],
  },
  prod_004: {
    id: 'prod_004',
    name: 'Lechuga Costina',
    category: 'verdura',
    unit: 'un',
    step: 1,
    basePrice: 1200,
    isSwappable: true,
    inSeason: true,
    imageUrl: 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?auto=format&fit=crop&q=80&w=300',
    tags: ['fresco'],
  },
  prod_005: {
    id: 'prod_005',
    name: 'Limón de Pica',
    category: 'fruta',
    unit: 'kg',
    step: 0.5,
    basePrice: 2000,
    isSwappable: true,
    inSeason: true,
    imageUrl: 'https://images.unsplash.com/photo-1590502593747-422e08d114ce?auto=format&fit=crop&q=80&w=300',
    tags: ['local'],
  },
  extra_001: {
    id: 'extra_001',
    name: 'Huevos de Campo',
    category: 'extra',
    unit: 'docena',
    step: 1,
    basePrice: 3500,
    isSwappable: false,
    inSeason: true,
    imageUrl: 'https://images.unsplash.com/photo-1587486913049-53fc88980cfc?auto=format&fit=crop&q=80&w=300',
    tags: ['gallinas libres'],
  },
  extra_002: {
    id: 'extra_002',
    name: 'Miel de Abeja',
    category: 'extra',
    unit: 'frasco 500g',
    step: 1,
    basePrice: 5000,
    isSwappable: false,
    inSeason: true,
    imageUrl: 'https://images.unsplash.com/photo-1587049352847-4d4b12b1413e?auto=format&fit=crop&q=80&w=300',
    tags: ['artesanal'],
  },
};

export const BOX_TEMPLATES: BoxTemplate[] = [
  {
    id: 'caja_individual',
    name: 'Caja Individual',
    description: 'Perfecta para 1-2 personas. Lo esencial para la semana.',
    basePrice: 12000,
    imageUrl: 'https://images.unsplash.com/photo-1608686207856-001b95cf60ca?auto=format&fit=crop&q=80&w=600',
    baseItems: [
      { productId: 'prod_001', defaultQty: 1, locked: false },
      { productId: 'prod_002', defaultQty: 0.5, locked: false },
      { productId: 'prod_003', defaultQty: 1, locked: false },
      { productId: 'prod_004', defaultQty: 1, locked: false },
    ],
  },
  {
    id: 'caja_familiar',
    name: 'Caja Familiar',
    description: 'La favorita para la semana. Ideal para 3-4 personas.',
    basePrice: 18000,
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=80&w=600',
    baseItems: [
      { productId: 'prod_001', defaultQty: 2, locked: false },
      { productId: 'prod_002', defaultQty: 1, locked: false },
      { productId: 'prod_003', defaultQty: 1.5, locked: false },
      { productId: 'prod_004', defaultQty: 2, locked: false },
      { productId: 'prod_005', defaultQty: 1, locked: false },
    ],
  },
  {
    id: 'caja_abundante',
    name: 'Caja Abundante',
    description: 'Para familias grandes y comilones. ¡No falta nada!',
    basePrice: 25000,
    imageUrl: 'https://images.unsplash.com/photo-1596199050105-6d5d32222916?auto=format&fit=crop&q=80&w=600',
    baseItems: [
      { productId: 'prod_001', defaultQty: 3, locked: false },
      { productId: 'prod_002', defaultQty: 2, locked: false },
      { productId: 'prod_003', defaultQty: 2, locked: false },
      { productId: 'prod_004', defaultQty: 3, locked: false },
      { productId: 'prod_005', defaultQty: 2, locked: false },
    ],
  },
];

export const AVAILABLE_SWAPS = Object.values(PRODUCTS).filter(p => p.isSwappable);
export const EXTRAS = Object.values(PRODUCTS).filter(p => p.category === 'extra');
